In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras.layers import Dense
from keras.models import Sequential

import numpy as np

In [3]:
tran = np.genfromtxt('transfusion.csv', delimiter=',')

X = tran[:,0:4]
y = tran[:,4]

In [5]:
print(X)

[[2.00e+00 5.00e+01 1.25e+04 9.80e+01]
 [0.00e+00 1.30e+01 3.25e+03 2.80e+01]
 [1.00e+00 1.60e+01 4.00e+03 3.50e+01]
 ...
 [2.30e+01 3.00e+00 7.50e+02 6.20e+01]
 [3.90e+01 1.00e+00 2.50e+02 3.90e+01]
 [7.20e+01 1.00e+00 2.50e+02 7.20e+01]]


In [6]:
print(y)

[1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1.
 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.
 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1.

In [7]:
print(type(X))

<class 'numpy.ndarray'>


In [8]:
print(X.shape)

(748, 4)


In [9]:
print(y.shape)

(748,)


In [10]:
#Creating a MLP multilayer perceprtron model using the keras layers

mlp_sequential = Sequential()

mlp_sequential.add(Dense(8, input_dim=4, init='uniform', activation='relu'))

mlp_sequential.add(Dense(6, init='uniform', activation='relu'))

/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, input_dim=4, activation="relu", kernel_initializer="uniform")`
  """
/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="uniform")`
  import sys


In [11]:
mlp_sequential.add(Dense(1, init='uniform', activation='sigmoid'))

/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [12]:
mlp_sequential.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [15]:
mlp_sequential.fit(X,y, nb_epoch=200, batch_size=8, verbose=0)

/home/aman/anaconda3/lib/python3.7/site-packages/keras/models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '



Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor








In [16]:
accuracy = mlp_sequential.evaluate(X,y)

 32/748 [>.............................] - ETA: 1s

In [17]:
print("Accuracy: %.2f%% " % (accuracy[1]*100))

Accuracy: 76.20% 


In [19]:
from keras.optimizers import SGD

In [20]:
opt = SGD(lr=0.01)

In [22]:
mlp_optim = Sequential()

mlp_optim.add(Dense(8, input_dim=4, init='uniform', activation='relu'))
mlp_optim.add(Dense(6, init='uniform', activation='relu'))
mlp_optim.add(Dense(1, init='uniform', activation='sigmoid'))




/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, input_dim=4, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  """


In [23]:
#Compiling the model with SGD
mlp_optim.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

In [24]:
#Fitting the model and checking the accuracy
mlp_optim.fit(X,y, validation_split=0.3, nb_epoch=150, batch_size=10,verbose=0)

/home/aman/anaconda3/lib/python3.7/site-packages/keras/models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


In [25]:
result_ptim = mlp_optim.evaluate(X,y)

 32/748 [>.............................] - ETA: 0s

In [27]:
print(f'Accuracy of the model {result_ptim[1]*100}')

Accuracy of the model 76.20320855614973
