In [1]:
import numpy as np #Importing numpy library 

In [2]:
#Craeting numpy array with float variable
a = np.array([1,2,3,4,5], float)

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
#Operations on numpy arrayu
#Replacing the first element of the array
a[0] = 5
print(a)

[5. 2. 3. 4. 5.]


In [5]:
b = np.array([[5,6,7],[3,4,5]], float)

In [6]:
print(b)

[[5. 6. 7.]
 [3. 4. 5.]]


In [7]:
print(b.shape)

(2, 3)


In [8]:
print(b.dtype)

float64


In [9]:
print(len(b))

2


In [10]:
2 in b

False

In [11]:
3 in b

True

In [12]:
#Reshape transformation from 1D to 2D

c = np.array(range(12), float)
print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [15]:
print(c.shape)

(12,)


In [16]:
c = c.reshape((2,6))

In [17]:
print(c)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]


In [18]:
print(c.shape)

(2, 6)


In [19]:
c.fill(0)

In [20]:
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
c.transpose()

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
c.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
#concatenation of two or more array
m = np.array([1,2], float)
n = np.array([3,4,5,6], float)

In [25]:
p = np.concatenate((m,n))

In [26]:
print(p)

[1. 2. 3. 4. 5. 6.]


In [27]:
print(p.shape)

(6,)


In [29]:
#use of newaxis to increase the dimensionality of the array
q = np.array([1,1,2], float)

In [31]:
z = q[:, np.newaxis]

In [32]:
print(z)

[[1.]
 [1.]
 [2.]]


In [33]:
print(z.shape)

(3, 1)


In [34]:
#adding two array using numpy
a = np.array([1,2,3], float)
b = np.array([[2,3,4],[5,6,7]], float)

In [35]:
print(a+b)

[[ 3.  5.  7.]
 [ 6.  8. 10.]]


In [37]:
print(b.mean(axis=0))

[3.5 4.5 5.5]


In [38]:
print(b.mean(axis=1))

[3. 6.]


In [39]:
print(b)

[[2. 3. 4.]
 [5. 6. 7.]]


In [41]:
#np.where function contains the conditional statement inside it 
np.where(a!=0, 1/a, a)

array([1.        , 0.5       , 0.33333333])

In [42]:
print(a)

[1. 2. 3.]


In [43]:
np.random.rand(2,3)

array([[0.02294147, 0.82612453, 0.80085564],
       [0.67755856, 0.27182736, 0.20901857]])

In [44]:
np.random.randint(2,3)

2

In [45]:
np.random.randn(2,3)

array([[-1.74825761,  1.02159842,  1.22363318],
       [-1.00429847, -0.61788246, -0.61399532]])

In [47]:
np.random.random_integers(2,3)

/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(2, 3 + 1) instead
  """Entry point for launching an IPython kernel.


2

In [49]:
np.random.random_sample(2)

array([0.42709486, 0.67871744])