In [1]:
import scipy
import numpy as np

In [2]:
from scipy import linalg
mat = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [3]:
print(mat)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [6]:
#Determinant of the matrix
print(linalg.det(mat))

-8.881784197001252e-16


In [7]:
#Inverse of the matrix
print(linalg.inv(mat))

[[ 1.7156570e+15 -4.2891425e+15  2.5734855e+15]
 [-3.4313140e+15  8.5782850e+15 -5.1469710e+15]
 [ 1.7156570e+15 -4.2891425e+15  2.5734855e+15]]


In [8]:
#Singular Value Decomposition
comp_1, comp_2, comp_3 = linalg.svd(mat)

In [9]:
print(comp_1)

[[-0.23498172  0.91625348  0.32444284]
 [-0.56747984  0.14167532 -0.81110711]
 [-0.78914525 -0.37471012  0.48666426]]


In [10]:
print(comp_2)

[1.54611193e+01 9.76621976e-01 9.43299524e-17]


In [11]:
print(comp_3)

[[-0.46825669 -0.57119923 -0.67414176]
 [-0.78362555 -0.08405223  0.6155211 ]
 [-0.40824829  0.81649658 -0.40824829]]


In [14]:
#scipy stats module
from scipy import stats

#Normal Distribution
#Generating a random values wih mean = 3 and the standard deviation = 5 using the function
data = stats.norm.rvs(3,5, size=20)

In [15]:
print(data)

[ 2.77455738e+00 -3.87740756e-01  7.59723209e+00  7.09458634e+00
  1.81506356e+00  5.28145699e+00  4.63734443e+00  2.72547529e-03
 -1.87720962e+00 -6.29490696e-01  3.65884949e+00  2.20515015e+00
 -1.13150036e+00 -4.16945923e+00 -3.68654441e+00  1.08336132e+01
  1.42247001e+00 -8.78292452e+00 -4.87750115e+00 -2.89489674e-01]


In [16]:
#Cdf of the beta distribution of the data with a = 100, b=130 as the shape parameters and the random variable of 0.34
cdf = scipy.stats.beta.cdf(0.34, a=100, b=134)

In [17]:
print(cdf)

0.002865479220153413
